2024-10-18 16:49:43,874 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\pythonProjects\lesson0\pythonProject12\tests_12_4.py", line 28, in test_run
    runner2 = rt.Runner(name=10, speed=10)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pythonProjects\lesson0\pythonProject12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-18 16:49:43,879 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\pythonProjects\lesson0\pythonProject12\tests_12_4.py", line 17, in test_walk
    runner1 = rt.Runner(name='Пешеход', speed=-100)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pythonProjects\lesson0\pythonProject12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -100
